"""create customers table

Revision ID: 874d0b6369c3
Revises: 05c1ac5a4fac
Create Date: 2026-02-27 21:03:27.898165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '874d0b6369c3'
down_revision = '05c1ac5a4fac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=False),
    sa.Column('contact_email', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customers')
    # ### end Alembic commands ###
