"""add subscription status to customer

Revision ID: ed6c0dc5fcbe
Revises: 874d0b6369c3
Create Date: 2026-02-28 20:05:27.792342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed6c0dc5fcbe'
down_revision = '874d0b6369c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('subscription_status')

    # ### end Alembic commands ###
